# Generated by Django 4.0 on 2023-05-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='hedline',
            new_name='headline',
        ),
    ]
