# Generated by Django 4.0 on 2023-06-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieReview',
        ),
    ]
